# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.19"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.19"
  i386: "ghcr.io/home-assistant/i386-base-python:3.12-alpine3.19"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: iSponsorBlockTV add-on"
  org.opencontainers.image.description: "Skip sponsor segments in YouTube videos playing on an Apple TV."
  org.opencontainers.image.source: "https://github.com/dmunozv04/iSponsorBlockTV"
  org.opencontainers.image.licenses: "GNU General Public License v3.0"
args:
  TEMPIO_VERSION: "2021.09.0"
